"""empty message

Revision ID: 0b6b45c5764e
Revises: 2522eb38baae
Create Date: 2019-05-29 20:58:39.378847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b6b45c5764e'
down_revision = '2522eb38baae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group', 'active')
    # ### end Alembic commands ###
