"""empty message

Revision ID: 37b1d6074517
Revises: 0b6b45c5764e
Create Date: 2019-05-29 21:14:53.493308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37b1d6074517'
down_revision = '0b6b45c5764e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('lora_id', sa.String(length=14), nullable=True))
    op.create_index(op.f('ix_group_lora_id'), 'group', ['lora_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_group_lora_id'), table_name='group')
    op.drop_column('group', 'lora_id')
    # ### end Alembic commands ###
