"""add button in group

Revision ID: 60e11569257e
Revises: 4c1bb919d661
Create Date: 2019-05-25 12:12:57.282791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60e11569257e'
down_revision = '4c1bb919d661'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('button', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group', 'button')
    # ### end Alembic commands ###
