"""empty message

Revision ID: c225a7326a4b
Revises: 211e053d792f
Create Date: 2019-06-10 02:05:11.678767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c225a7326a4b'
down_revision = '211e053d792f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_group_lora_id', table_name='group')
    op.create_index(op.f('ix_group_lora_id'), 'group', ['lora_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_group_lora_id'), table_name='group')
    op.create_index('ix_group_lora_id', 'group', ['lora_id'], unique=1)
    # ### end Alembic commands ###
