"""empty message

Revision ID: cb01788112ec
Revises: 60e11569257e
Create Date: 2019-05-27 22:41:33.998454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb01788112ec'
down_revision = '60e11569257e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idworker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=14), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_idworker_uid'), 'idworker', ['uid'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_idworker_uid'), table_name='idworker')
    op.drop_table('idworker')
    # ### end Alembic commands ###
